{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.963.0 (23.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Salary DIM\",\"Tech\",\"posting\",\"Jobs ID\",\"_Measures\",\"Time\",\"Mandatory skills\",\"Optional skills\",\"Contract types DIM\",\"Currencies DIM\",\"Technology DIM\",\"Location DIM\",\"Seniority DIM\",\"Category DIM\",\"Unique Jobs DIM\",\"Job Group\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pl-PL",
    "cultures": [
      {
        "name": "pl-PL",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "posting",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Źródło = Json.Document(Web.Contents(\"https://nofluffjobs.com/api/posting\")),",
          "    postings = Źródło[postings],",
          "    #\"Przekonwertowane na tabelę\" = Table.FromList(postings, Splitter.SplitByNothing(), null, null, ExtraValues.Error)",
          "in",
          "    #\"Przekonwertowane na tabelę\""
        ],
        "kind": "m",
        "lineageTag": "94d9605b-d18d-4e4f-91e0-9abb568cdbcf"
      },
      {
        "name": "Tech",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Źródło = posting,",
          "    #\"Rozwinięty element Column1\" = Table.ExpandRecordColumn(Źródło, \"Column1\", {\"id\", \"technology\", \"category\", \"flavors\"}, {\"Column1.id\", \"Column1.technology\", \"Column1.category\", \"Column1.flavors\"}),",
          "    #\"Rozwinięty element Column1.flavors\" = Table.ExpandListColumn(#\"Rozwinięty element Column1\", \"Column1.flavors\"),",
          "    #\"Usunięto duplikaty\" = Table.Distinct(#\"Rozwinięty element Column1.flavors\"),",
          "    #\"Zmieniono nazwy kolumn\" = Table.RenameColumns(#\"Usunięto duplikaty\",{{\"Column1.id\", \"ID\"}, {\"Column1.technology\", \"Technology\"}, {\"Column1.category\", \"Category\"}, {\"Column1.flavors\", \"Flavors\"}}),",
          "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Zmieniono nazwy kolumn\",{{\"ID\", type text}, {\"Technology\", type text}, {\"Category\", type text}, {\"Flavors\", type text}}),",
          "    #\"Oczyszczono tekst\" = Table.TransformColumns(#\"Zmieniono typ\",{{\"Technology\", Text.Clean, type text}}),",
          "    #\"Tekst pisany małymi literami\" = Table.TransformColumns(#\"Oczyszczono tekst\",{{\"Technology\", Text.Lower, type text}}),",
          "    #\"Zmieniono pierwszą literę każdego wyrazu na wielką\" = Table.TransformColumns(#\"Tekst pisany małymi literami\",{{\"Technology\", Text.Proper, type text}})",
          "in",
          "    #\"Zmieniono pierwszą literę każdego wyrazu na wielką\""
        ],
        "kind": "m",
        "lineageTag": "0e0e98e2-5ea7-4db4-aefa-bde826fc1103"
      }
    ],
    "relationships": [
      {
        "name": "434b8ace-a039-4bcc-933d-859f2c0b7bc4",
        "fromColumn": "PostedDate",
        "fromTable": "Time",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_38665d87-a668-4f23-945d-d8ab18ba6af4"
      },
      {
        "name": "6f358939-556a-4053-bfca-50a4828e8e2f",
        "fromColumn": "RenewedDate",
        "fromTable": "Time",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_815af6cc-39a4-42fc-a4c4-2fd311b72361"
      },
      {
        "name": "1da910e1-4afe-4080-aa18-f1488a6c3c61",
        "fromColumn": "Seniority",
        "fromTable": "Jobs ID",
        "toColumn": "Seniorty",
        "toTable": "Seniority DIM"
      },
      {
        "name": "4b7f55fc-b6ad-4c1a-952f-85ce23ebe229",
        "fromColumn": "Category",
        "fromTable": "Jobs ID",
        "toColumn": "Category",
        "toTable": "Category DIM"
      },
      {
        "name": "36974e3a-7b8f-4f6f-b292-3c42ad6d1888",
        "fromColumn": "Currency",
        "fromTable": "Salary DIM",
        "toColumn": "Currency",
        "toTable": "Currencies DIM"
      },
      {
        "name": "b3826663-365c-4922-b5ff-9b5cfb466fc6",
        "fromColumn": "Contract type",
        "fromTable": "Salary DIM",
        "toColumn": "Contract type",
        "toTable": "Contract types DIM"
      },
      {
        "name": "3d2ba6c6-9824-4297-8de4-e74d352f9571",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ID",
        "fromTable": "Jobs ID",
        "toColumn": "ID",
        "toTable": "Salary DIM"
      },
      {
        "name": "85775422-22b4-495c-b570-6ba7019ba9c3",
        "fromColumn": "Technology",
        "fromTable": "Jobs ID",
        "toColumn": "Technology",
        "toTable": "Technology DIM"
      },
      {
        "name": "d3c1c413-e472-44ac-8872-205d504f14cc",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "company--title",
        "fromTable": "Jobs ID",
        "toColumn": "Company--title",
        "toTable": "Unique Jobs DIM"
      },
      {
        "name": "fa226cc4-a2dd-4866-acd6-13caa6094310",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Company--title",
        "fromTable": "Optional skills",
        "toColumn": "Company--title",
        "toTable": "Unique Jobs DIM"
      },
      {
        "name": "d4c26a3f-78cd-4977-ad21-13616412950e",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Company--title",
        "fromTable": "Mandatory skills",
        "toColumn": "Company--title",
        "toTable": "Unique Jobs DIM"
      },
      {
        "name": "0c55951a-7225-44a4-8aba-5142264a974a",
        "fromColumn": "Group",
        "fromTable": "Jobs ID",
        "toColumn": "Group",
        "toTable": "Job Group"
      }
    ],
    "sourceQueryCulture": "pl-PL",
    "tables": [
      {
        "name": "DateTableTemplate_5ce98111-93e3-4e3e-8715-c33b59400b29",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7c3be428-cfc3-4c75-9e12-5f473a014f7a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9e25dcaa-b5df-453c-8980-0578932f4a72",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8552fd7c-b8f2-493e-a365-94331fca83a0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c7ec036b-46a5-4023-aed4-90e7a5a7b139",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "76941ea8-91e4-4f8f-8982-15408fbdbc40",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Kwartał \" & [Numer kwartału]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "26c41cdd-31be-4d07-b389-583fc751a6f4",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2eaee434-3e77-4ab0-9827-ca560077d44a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "c8b6edb3-aec5-463a-a9f5-b7188ed3bf2f",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "419cc4a4-bd6e-49be-97b6-80e6b08291ae",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "2c7dc873-b305-46cf-ad8e-8c8b77dc6834",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "87d86ea7-61ef-4fc9-b6b5-378314c70bef",
                "ordinal": 3
              }
            ],
            "lineageTag": "3a147c9a-9074-49c2-ab6f-60f88be178ae"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "59f23e2f-eae5-4b60-87e6-43d35b12bde8",
        "partitions": [
          {
            "name": "DateTableTemplate_5ce98111-93e3-4e3e-8715-c33b59400b29-fa6a3d16-7d4b-41a6-80d9-a836c17e1471",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Seniority DIM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Seniorty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "72a33760-46e3-4d98-b885-50e15fa03a69",
            "sortByColumn": "Seniority Order",
            "sourceColumn": "Seniorty",
            "summarizeBy": "none"
          },
          {
            "name": "Seniority Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6114e4c2-a3ec-453b-95eb-7dabe70147fe",
            "sourceColumn": "Seniority Order",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55a3dd63-9689-4081-aab1-013a45461e3d",
        "partitions": [
          {
            "name": "Seniority DIM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = posting,",
                "    #\"Rozwinięty element Column1\" = Table.ExpandRecordColumn(Źródło, \"Column1\", { \"seniority\"}, { \"Column1.seniority\"}),",
                "    #\"Rozwinięty element Column1.seniority\" = Table.ExpandListColumn(#\"Rozwinięty element Column1\", \"Column1.seniority\"),",
                "    #\"Usunięto duplikaty\" = Table.Distinct(#\"Rozwinięty element Column1.seniority\"),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Usunięto duplikaty\",{{\"Column1.seniority\", type text}}),",
                "    #\"Zmieniono nazwy kolumn\" = Table.RenameColumns(#\"Zmieniono typ\",{{\"Column1.seniority\", \"Seniorty\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Zmieniono nazwy kolumn\", \"Seniority Order\", each if [Seniorty] = \"Trainee\" then 0 ",
                "else if [Seniorty] = \"Junior\" then 1 ",
                "else if [Seniorty] = \"Mid\" then 2 ",
                "else if [Seniorty] = \"Senior\" then 3 ",
                "else 4),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Seniority Order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Jobs ID",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad6e40ab-f197-4124-a858-adef919d0b9a",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10d02bfb-9ded-4141-8945-282259f9dd65",
            "sourceColumn": "Company",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73f47358-0e47-4a92-ba1f-4fb07651f2ec",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "company--title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "007687e2-816d-4c4e-bcbc-5d6a59cdcc51",
            "sourceColumn": "company--title",
            "summarizeBy": "none"
          },
          {
            "name": "Salary from",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4e0b089-d1cd-479f-8697-9c40113060ca",
            "sourceColumn": "Salary from",
            "summarizeBy": "sum"
          },
          {
            "name": "Salary to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8fb4142-5b00-4926-bfc0-819feee6efdb",
            "sourceColumn": "Salary to",
            "summarizeBy": "sum"
          },
          {
            "name": "Salary Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f08201e1-c248-45aa-a7a3-a7cc93b72eab",
            "sourceColumn": "Salary Type",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9601d99c-9ad7-43a3-bbab-83e7869caae5",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "LocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6285e77-c182-40b9-9475-40b50541fbe0",
            "sourceColumn": "LocationID",
            "summarizeBy": "none"
          },
          {
            "name": "Seniority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d27a4cde-5eee-4b47-9529-0660d38e8186",
            "sourceColumn": "Seniority",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "faa85bfa-0147-4068-bcad-ff262c66d247",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Technology",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8609001e-e673-4131-8e5b-d6a5c74ca47e",
            "sourceColumn": "Technology",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c75ab5b-b22f-42a8-8119-11624ddb1c3a",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "84a57617-b5b1-46a7-8658-4dce93d506d3",
        "partitions": [
          {
            "name": "Jobs ID",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = posting,",
                "    #\"Rozwinięty element Column1\" = Table.ExpandRecordColumn(Źródło, \"Column1\", {\"category\", \"id\", \"location\", \"name\", \"salary\", \"seniority\", \"technology\", \"title\"}, {\"Column1.category\", \"Column1.id\", \"Column1.location\", \"Column1.name\", \"Column1.salary\", \"Column1.seniority\", \"Column1.technology\", \"Column1.title\"}),",
                "    #\"Expanded Column1.seniority\" = Table.ExpandListColumn(#\"Rozwinięty element Column1\", \"Column1.seniority\"),",
                "    #\"Expanded Column1.location\" = Table.ExpandRecordColumn(#\"Expanded Column1.seniority\", \"Column1.location\", {\"places\"}, {\"Column1.location.places\"}),",
                "    #\"Expanded Column1.location.places\" = Table.ExpandListColumn(#\"Expanded Column1.location\", \"Column1.location.places\"),",
                "    #\"Expanded Column1.location.places1\" = Table.ExpandRecordColumn(#\"Expanded Column1.location.places\", \"Column1.location.places\", {\"city\", \"country\"}, {\"Column1.location.places.city\", \"Column1.location.places.country\"}),",
                "    #\"Expanded Column1.location.places.country\" = Table.ExpandRecordColumn(#\"Expanded Column1.location.places1\", \"Column1.location.places.country\", {\"name\"}, {\"Column1.location.places.country.name\"}),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Expanded Column1.location.places.country\",{\"Column1.location.places.country.name\", \"Column1.location.places.city\"},Combiner.CombineTextByDelimiter(\"-\", QuoteStyle.None),\"LocationID\"),",
                "    #\"Expanded Column1.salary\" = Table.ExpandRecordColumn(#\"Merged Columns\", \"Column1.salary\", {\"from\", \"to\", \"type\", \"currency\"}, {\"Column1.salary.from\", \"Column1.salary.to\", \"Column1.salary.type\", \"Column1.salary.currency\"}),",
                "    #\"Zmieniono nazwy kolumn\" = Table.RenameColumns(#\"Expanded Column1.salary\",{{\"Column1.id\", \"ID\"}, {\"Column1.name\", \"Company\"}, {\"Column1.title\", \"Title\"}, {\"Column1.salary.from\", \"Salary from\"}, {\"Column1.salary.to\", \"Salary to\"}, {\"Column1.salary.type\", \"Salary Type\"}, {\"Column1.salary.currency\", \"Currency\"}, {\"Column1.seniority\", \"Seniority\"}, {\"Column1.category\", \"Category\"}, {\"Column1.technology\", \"Technology\"}}),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Zmieniono nazwy kolumn\",{{\"ID\", type text}, {\"Company\", type text}, {\"Title\", type text}, {\"Salary from\", Int64.Type}, {\"Salary to\", Int64.Type}, {\"Salary Type\", type text}, {\"Currency\", type text}, {\"Seniority\", type text}, {\"Category\", type text}}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Zmieniono typ\",{{\"Company\", Text.Clean, type text}, {\"Title\", Text.Clean, type text}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Cleaned Text\",{\"Category\", \"ID\", \"LocationID\", \"Company\", \"Title\", \"Salary from\", \"Salary to\", \"Salary Type\", \"Currency\", \"Seniority\", \"Technology\"}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Reordered Columns\",{{\"Title\", Text.Trim, type text}, {\"Company\", Text.Trim, type text}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Title\", Text.Upper, type text}, {\"Company\", Text.Upper, type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Uppercased Text\", \"company--title\", each [Company] & \"--\" & [Title]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"company--title\", type text}, {\"Technology\", type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\"),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Removed Duplicates\", \"Group\", each if [Technology] is null or [Technology] = \"\" then \"Non-tech\" else \"Tech\")",
                "in",
                "    #\"Added Custom1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Kolumna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "26d4c297-66e2-462a-a453-ed266039c8ed",
            "sourceColumn": "Kolumna 1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9c6f3896-b824-4110-a225-e78fe0a91a23",
        "measures": [
          {
            "name": "Job offerts",
            "displayFolder": "Counts",
            "expression": [
              "",
              "var cnt = COUNT('Salary DIM'[ID])",
              "var valueToReturn = ",
              "    IF(",
              "        ISBLANK(cnt),",
              "        0,",
              "        cnt)",
              "return valueToReturn"
            ],
            "formatString": "0",
            "lineageTag": "77ea82a6-4d3b-4c43-af9c-467854d2e59e"
          },
          {
            "name": "Average Salaty",
            "displayFolder": "Salary\\AVG",
            "expression": [
              "",
              "var sumMin = SUM('Jobs ID'[Salary from])",
              "var sumMax = SUM('Jobs ID'[Salary to])",
              "var countSalaryRows = COUNTROWS('Jobs ID')",
              "var averageSalary = (sumMax + sumMin) / (countSalaryRows * 2)",
              "var valueToReturn = IF(",
              "    ISBLANK(averageSalary),",
              "    \"No jobs\", ",
              "    averageSalary)",
              "return valueToReturn"
            ],
            "formatString": "0",
            "lineageTag": "d75a7bca-ffe3-467d-ade5-a65c207f6267"
          },
          {
            "name": "Most Popular Technology",
            "displayFolder": "KPI",
            "expression": [
              "",
              "var mostPopularTechTable = ",
              "    ADDCOLUMNS(",
              "        DISTINCT('Technology DIM'[Technology Pretty]), ",
              "        \"Cnt\", [Jobs])",
              "var techMaxCnt = MAXX(mostPopularTechTable, [Cnt])",
              "var mostPopularTech = ",
              "    FILTER(",
              "        mostPopularTechTable, ",
              "        [Cnt] = techMaxCnt && [Cnt] <> 0",
              "        )",
              "var technology = CONCATENATEX(mostPopularTech,[Technology Pretty], \" & \")",
              "var nonTechJobCNT = COUNTROWS('Salary DIM')",
              "var isBlankTech = ISBLANK(technology)",
              "var valueToReturn =  ",
              "    IF(",
              "        isBlankTech && nonTechJobCNT =0,",
              "        \"No job offerts\",",
              "        IF(",
              "            isBlankTech,",
              "            \"No tech jobs\", ",
              "            technology))",
              "return",
              "   valueToReturn"
            ],
            "lineageTag": "39539f1e-d7ae-4813-b910-1dc0f52828ff"
          },
          {
            "name": "Best Payed Technology",
            "displayFolder": "KPI",
            "expression": [
              "",
              "var techAverageSalary = ",
              "    ADDCOLUMNS(",
              "        'Technology DIM', ",
              "        \"Average\", [Average Salaty])",
              "",
              "var topOneSalary = ",
              "    MAXX(techAverageSalary, [Average])",
              "",
              "var topSalary = ",
              "    FILTER(",
              "        techAverageSalary, ",
              "        [Average] = topOneSalary && [Average] <> 0)",
              "",
              "var technologies = CONCATENATEX(topSalary,[Technology Pretty], \" & \")",
              "var nonTechJobCNT = COUNTROWS('Salary DIM')",
              "var isBlankTech = ISBLANK(technologies)",
              "var valueToReturn = IF(",
              "    isBlankTech && nonTechJobCNT = 0,",
              "    \"No job offerts\",",
              "    IF(isBlankTech,",
              "    \"No tech jobs\",",
              "    technologies))",
              "RETURN",
              "    valueToReturn"
            ],
            "lineageTag": "562b0ea1-c383-4619-aefb-6def496b02ed"
          },
          {
            "name": "Most Popular Category",
            "displayFolder": "KPI",
            "expression": [
              "",
              "var category = ",
              "    ADDCOLUMNS(",
              "        'Category DIM',",
              "        \"CNT\",",
              "        [Jobs])",
              "var topCategory = ",
              "    MAXX(category, [CNT])",
              "var categories = ",
              "    CONCATENATEX(",
              "        FILTER(category, ",
              "        [CNT] = topCategory && [CNT] <> 0),",
              "        'Category DIM'[Category - Pretty]",
              "    ,\" & \")",
              "var nonTechJobCNT = COUNTROWS('Salary DIM')",
              "var isBlankCategory = ISBLANK(categories)",
              "var valueToReturn = ",
              "    IF(",
              "        isBlankCategory && nonTechJobCNT = 0,",
              "        \"No job offerts\", ",
              "        IF(isBlankCategory,",
              "        \"No tech jobs\",",
              "        categories))",
              "return ",
              "    valueToReturn"
            ],
            "lineageTag": "da3091b4-fd93-4dcc-acdd-e7f8fd588854"
          },
          {
            "name": "Average Salary Seniority General",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Salary\\AVG",
            "expression": [
              "",
              "var avgSalaryWithoutSenioroty = CALCULATE([Average Salaty], ALL('Seniority DIM'))",
              "return",
              "    avgSalaryWithoutSenioroty"
            ],
            "lineageTag": "b1db4bfc-0aa9-41bc-a9bf-8186d21b3fa0"
          },
          {
            "name": "Jobs",
            "displayFolder": "Counts",
            "expression": "COUNTROWS('Salary DIM')",
            "formatString": "0",
            "lineageTag": "d9191273-a21e-4f65-9b1d-46a4ff2067ff"
          },
          {
            "name": "Average Salary Seniority General 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Salary\\AVG",
            "expression": [
              "",
              "var avgSalaryWithoutSenioroty = CALCULATE([Average Salaty], ALL('Seniority DIM'))",
              "return",
              "    avgSalaryWithoutSenioroty"
            ],
            "lineageTag": "daabbf75-d4ba-4e1d-90a4-3aa3141db219"
          },
          {
            "name": "Salary AVG From",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "AVERAGE('Jobs ID'[Salary from])",
            "formatString": "0",
            "lineageTag": "12f85278-4d21-49ab-a9ba-61d3eca65ba5"
          },
          {
            "name": "Salary AVG To",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "AVERAGE('Jobs ID'[Salary to])",
            "formatString": "0",
            "lineageTag": "c471103c-b722-46f5-aaca-758296e8d696"
          },
          {
            "name": "% vs From ALL",
            "expression": [
              "",
              "var avgFrom = [Salary AVG From]",
              "var isSelectedCategory = ISBLANK([Selected Category])",
              "var isSelectedTechnology = ISBLANK([Selected Tech])",
              "",
              "var valueToReturn = ",
              "    IF(isSelectedCategory && isSelectedTechnology,",
              "    BLANK(),",
              "    IF(NOT isSelectedTechnology,",
              "        1,",
              "        2))",
              "        ",
              "return valueToReturn"
            ],
            "formatString": "0",
            "lineageTag": "3f4d3c11-4a66-4b3a-b2dd-ad9cf51ea07c"
          },
          {
            "name": "% vs To ALL",
            "expression": "0",
            "formatString": "0",
            "lineageTag": "7ba18c70-5de0-45d8-84cb-7018d6d3affc"
          },
          {
            "name": "Selected Tech",
            "expression": "SELECTEDVALUE('Technology DIM'[Technology Pretty], BLANK())",
            "lineageTag": "e491e5e7-c759-4daa-aea0-a2be6bd62886"
          },
          {
            "name": "Selected Category",
            "expression": "SELECTEDVALUE('Category DIM'[Category], BLANK())",
            "lineageTag": "c2f114ee-5d34-4cae-855a-dcdb61b673a9"
          },
          {
            "name": "% of Average",
            "expression": [
              "",
              "var techValue = SELECTEDVALUE('Technology DIM'[Technology], BLANK())",
              "var categoryValue = SELECTEDVALUE('Category DIM'[Category], BLANK())",
              "",
              "var techTest = NOT ISBLANK(techValue)",
              "var categoryTest = NOT ISBLANK(categoryValue)",
              "",
              "var avgSalaryFrom = [Salary AVG From]",
              "var avgSalaryTo = [Salary AVG To]",
              "",
              "var categoryFrom = ROUND(CALCULATE([Salary AVG From], ",
              "                            ALL('Technology DIM'), ",
              "                            ALL('Jobs ID'[Company]))",
              "                            ,0)",
              "var categoryTo = ROUND(CALCULATE([Salary AVG To], ",
              "                            ALL('Technology DIM'), ",
              "                            ALL('Jobs ID'[Company]))",
              "                            ,0)",
              "",
              "var totalFrom = CALCULATE([Average Category From], ALL('Category DIM'))",
              "var totalTo = CALCULATE([Average Category To], ALL('Category DIM'))",
              "",
              "var technologyLevel = FORMAT(DIVIDE(avgSalaryFrom, categoryFrom), \"Percent\") & \" - \" & FORMAT(DIVIDE(avgSalaryTo, categoryTo), \"Percent\")",
              "var categoryLevel = FORMAT(DIVIDE(avgSalaryFrom, totalFrom), \"Percent\") & \" - \" & FORMAT(DIVIDE(avgSalaryTo, totalTo), \"Percent\")",
              "",
              "var avgSalaryTest = NOT ISBLANK(avgSalaryFrom)",
              "",
              "var test = IF(techTest && avgSalaryTest, technologyLevel, IF(categoryTest && avgSalaryTest, categoryLevel))",
              "return test"
            ],
            "lineageTag": "d30c7622-c4e9-412b-990d-b514252a70af"
          },
          {
            "name": "Previous level",
            "expression": [
              "",
              "var techTest = NOT ISBLANK(SELECTEDVALUE('Technology DIM'[Technology], BLANK()))",
              "var categoryTest = NOT ISBLANK(SELECTEDVALUE('Tech category DIM'[Category], BLANK()))",
              "var avgSalary = NOT ISBLANK([Salary AVG From])",
              "var test = IF(techTest && avgSalary, \"Category\", IF(categoryTest && avgSalary, \"Total\"))",
              "return test"
            ],
            "lineageTag": "9f4444d8-8fc9-4c31-b611-9813c50747e8"
          },
          {
            "name": "Average Category From",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "ROUND(CALCULATE([Salary AVG From], ",
              "                            ALL('Technology DIM'), ",
              "                            ALL('Jobs ID'[Company]))",
              "                            ,0)"
            ],
            "lineageTag": "75d27cad-174d-4aaa-ba02-b80205945e4b"
          },
          {
            "name": "Average Category To",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "ROUND(CALCULATE([Salary AVG To], ",
              "                            ALL('Technology DIM'), ",
              "                            ALL('Jobs ID'[Company]))",
              "                            ,0)"
            ],
            "lineageTag": "81f7411f-dab7-4b23-aae9-f40bda1961c2"
          },
          {
            "name": "Distinct jobs",
            "expression": "DISTINCTCOUNT('Jobs ID'[company--title])",
            "formatString": "0",
            "lineageTag": "3a4a9e18-d2af-4e15-96cf-4d7c418e2414"
          },
          {
            "name": "Technology title",
            "expression": [
              "",
              "var tech_selected = SELECTEDVALUE('Technology DIM'[Technology Pretty], \"Multiple technology\")",
              "var value_to_return = IF(ISBLANK(tech_selected),\"Not specified\", tech_selected)",
              "return value_to_return"
            ],
            "lineageTag": "4f94b5d3-c910-4375-a0e7-313e9847eb64"
          },
          {
            "name": "Mandatory skills cnt",
            "expression": "DISTINCTCOUNTNOBLANK('Mandatory skills'[Skill])",
            "formatString": "0",
            "lineageTag": "a54de293-8225-4ea5-8440-ff727b79f8b0"
          },
          {
            "name": "Average skills required per jobs",
            "expression": [
              "",
              "var skills_per_job = ADDCOLUMNS('Unique Jobs DIM', \"CNT\", [Mandatory skills cnt])",
              "var avg_of_cnt = AVERAGEX(skills_per_job, [CNT])",
              "return avg_of_cnt"
            ],
            "formatString": "0",
            "lineageTag": "21a3ef7e-9c20-4987-92f8-51de6c1e27a2"
          },
          {
            "name": "Unique Average Salary",
            "displayFolder": "KPI\\Salary",
            "expression": [
              "",
              "var unique_jobs_salary = ADDCOLUMNS('Unique Jobs DIM', \"Salary\", [Average Salaty])",
              "var average_salary = AVERAGEX(unique_jobs_salary, [Salary])",
              "var value_to_return =  IF(ISBLANK(average_salary), [No jobs text], average_salary)",
              "",
              "return value_to_return"
            ],
            "formatString": "0",
            "lineageTag": "dcd6aede-c0ff-458d-ade0-7fec53af85e1"
          },
          {
            "name": "Unique jobs count KPI",
            "displayFolder": "KPI\\Jobs",
            "expression": [
              "",
              "var cnt = DISTINCTCOUNT('Unique Jobs DIM'[Company--title])",
              "var value_to_return = IF(ISBLANK(cnt), [No jobs text], cnt)",
              "return value_to_return"
            ],
            "formatString": "0",
            "lineageTag": "f587bf0b-3e51-4aa4-ad40-563bceb0295a"
          },
          {
            "name": "Median Salary M",
            "displayFolder": "KPI\\Salary",
            "expression": [
              "",
              "var median_salary = MEDIANX('Salary DIM', 'Salary DIM'[Salary mid] )",
              "var value_to_return = IF(ISBLANK(median_salary),[No jobs text], median_salary)",
              "",
              "return value_to_return"
            ],
            "formatString": "0",
            "lineageTag": "91997e9f-44a5-4a46-862c-3f46b7767090"
          },
          {
            "name": "Top 20 Percent Avg",
            "displayFolder": "KPI\\Salary",
            "expression": [
              "",
              "var top_20_percent_cnt = ROUND(COUNTROWS('Salary DIM') * 0.2, 0)",
              "var top_20_percent = TOPN(top_20_percent_cnt, 'Salary DIM', 'Salary DIM'[Salary mid], DESC)",
              "var average_top_20 = AVERAGEX(",
              "    top_20_percent, [Salary mid])",
              "var value_to_return = IF(ISBLANK(average_top_20), [No jobs text], average_top_20)",
              "return value_to_return"
            ],
            "formatString": "0",
            "lineageTag": "3446722c-e6ef-4604-99f0-605236996e97"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "52a68f16-2e35-438a-9cab-19a9bd9c6f4a"
          },
          {
            "name": "Lowest 20 Percent Avg",
            "displayFolder": "KPI\\Salary",
            "expression": [
              "",
              "var bottom_20_percent_cnt = ROUND(COUNTROWS('Salary DIM') * 0.2, 0)",
              "var bottom_20_percent = TOPN(bottom_20_percent_cnt, 'Salary DIM', 'Salary DIM'[Salary mid], ASC)",
              "var average_bottom_20 = AVERAGEX(",
              "    bottom_20_percent, [Salary mid])",
              "var value_to_return = IF(ISBLANK(average_bottom_20), [No jobs text], average_bottom_20)",
              "return value_to_return"
            ],
            "formatString": "0",
            "lineageTag": "619644cf-843e-4600-abc1-95fccb6cf428"
          },
          {
            "name": "Average range",
            "expression": [
              "",
              "var range_min = ROUND(AVERAGE('Salary DIM'[Salary from]),0)",
              "var range_max = ROUND(AVERAGE('Salary DIM'[Salary to]),0)",
              "var format_to_return = range_min & \" - \" & range_max ",
              "var range_test = NOT ISBLANK(range_max)",
              "var return_value = IF(range_test, format_to_return, BLANK())",
              "return return_value"
            ],
            "lineageTag": "bd8ce97e-65cd-4e13-a8db-4bb9b78e2b5d"
          },
          {
            "name": "Mandatory skills",
            "expression": "VALUES('Mandatory skills'[Skill])",
            "lineageTag": "5cfaa877-5388-46e0-ba48-0ff4347ecf5b"
          },
          {
            "name": "Average mandatory skills",
            "expression": "AVERAGE('Mandatory skills'[Skill])",
            "formatString": "0",
            "lineageTag": "f8a17557-b187-4ca4-922a-82570ef1f077"
          },
          {
            "name": "Average skills required per jobs nice to have",
            "expression": [
              "",
              "var skills_per_job = ADDCOLUMNS('Unique Jobs DIM', \"CNT\", [Nice to have skills cnt])",
              "var avg_of_cnt = AVERAGEX(skills_per_job, [CNT])",
              "return avg_of_cnt"
            ],
            "formatString": "0",
            "lineageTag": "d582ece9-6a49-455e-960c-75558328cf0d"
          },
          {
            "name": "Nice to have skills cnt",
            "expression": "DISTINCTCOUNT('Optional skills'[Skill])",
            "formatString": "0",
            "lineageTag": "e2f06ef0-5c6c-4ff5-93b2-6cd36efaad82"
          },
          {
            "name": "Job offerts KPI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "KPI\\Jobs",
            "expression": [
              "",
              "var cnt = COUNT('Salary DIM'[ID])",
              "var valueToReturn = ",
              "    IF(",
              "        ISBLANK(cnt),",
              "        [No jobs text],",
              "        cnt)",
              "return valueToReturn"
            ],
            "formatString": "0",
            "lineageTag": "f55cbb53-032e-4395-9a0f-ac4a0b924053"
          },
          {
            "name": "Average skills KPI",
            "displayFolder": "KPI\\Jobs",
            "expression": [
              "",
              "var skills_cnt = [Average skills required per jobs]",
              "var value_to_return = IF(ISBLANK(skills_cnt), [No jobs text], skills_cnt)",
              "return value_to_return"
            ],
            "formatString": "0",
            "lineageTag": "ba087b69-70d6-4fa6-86c0-706b0c7ff4c8"
          },
          {
            "name": "No jobs text",
            "expression": "\"No jobs\"",
            "lineageTag": "93900bd9-f03f-428d-b47f-325aeced27a9"
          },
          {
            "name": "Average skills nice to have KPI",
            "displayFolder": "KPI\\Jobs",
            "expression": [
              "",
              "var skills_avg_cnt = [Average skills required per jobs nice to have]",
              "var value_to_return = IF(ISBLANK(skills_avg_cnt), [No jobs text], skills_avg_cnt)",
              "return value_to_return"
            ],
            "formatString": "0",
            "lineageTag": "95ad9c45-ad91-4dd7-bae8-e298a1887b16"
          },
          {
            "name": "Unique jobs count",
            "expression": [
              "",
              "var cnt = DISTINCTCOUNT('Unique Jobs DIM'[Company--title])",
              "return cnt"
            ],
            "formatString": "0",
            "lineageTag": "2f66f847-e06f-4393-aa0f-22c10e906e4d"
          },
          {
            "name": "Skills %",
            "expression": [
              "",
              "var id_count = [Unique jobs count]",
              "var all_jobs = CALCULATE([Unique jobs count], ALL('Mandatory skills'[Skill]))",
              "",
              "return id_count / all_jobs"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "69f81866-b4c5-4f51-832d-759f5e40bcb1"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Kolumna 1\" = _t])",
                "in",
                "    Źródło"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Time",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b7817a7-29fc-4902-b288-09ea8c775b22",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "PostedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "88a47f6f-4b90-4b6f-ac24-68e0dc3c4b27",
            "sourceColumn": "PostedDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Odmiana",
                "defaultHierarchy": {
                  "hierarchy": "Hierarchia dat",
                  "table": "LocalDateTable_38665d87-a668-4f23-945d-d8ab18ba6af4"
                },
                "isDefault": true,
                "relationship": "434b8ace-a039-4bcc-933d-859f2c0b7bc4"
              }
            ]
          },
          {
            "name": "RenewedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d28834c2-041c-474c-bc3c-35ce21b3faf1",
            "sourceColumn": "RenewedDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Odmiana",
                "defaultHierarchy": {
                  "hierarchy": "Hierarchia dat",
                  "table": "LocalDateTable_815af6cc-39a4-42fc-a4c4-2fd311b72361"
                },
                "isDefault": true,
                "relationship": "6f358939-556a-4053-bfca-50a4828e8e2f"
              }
            ]
          }
        ],
        "lineageTag": "b603d561-31da-4cf5-96af-43d39ce367ab",
        "partitions": [
          {
            "name": "Time",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = posting,",
                "    #\"Rozwinięty element Column1\" = Table.ExpandRecordColumn(Źródło, \"Column1\", {\"id\", \"posted\", \"renewed\"}, {\"id\", \"posted\", \"renewed\"}),",
                "    #\"Usunięto duplikaty\" = Table.Distinct(#\"Rozwinięty element Column1\"),",
                "    ",
                "    // Bezpieczna konwersja dla 'posted'",
                "    #\"Bezpieczna konwersja posted\" = Table.AddColumn(#\"Usunięto duplikaty\", \"UnixTimestampPosted\", each if [posted] = null then null else #duration(0, 0, 0, [posted] / 1000)),",
                "    // Konwersja na datatime dla 'posted'",
                "    #\"Bezpieczna data posted\" = Table.AddColumn(#\"Bezpieczna konwersja posted\", \"NewDateTimePosted\", each if [UnixTimestampPosted] = null then null else #datetimezone(1970, 1, 1, 0, 0, 0, 0, 0) + [UnixTimestampPosted]),",
                "",
                "    // Bezpieczna konwersja dla 'renewed'",
                "    #\"Bezpieczna konwersja renewed\" = Table.AddColumn(#\"Bezpieczna data posted\", \"UnixTimestamp Renewed\", each if [renewed] = null then null else #duration(0, 0, 0, [renewed] / 1000)),",
                "    // Konwersja na datatime dla 'renewed'",
                "    #\"Bezpieczna data renewed\" = Table.AddColumn(#\"Bezpieczna konwersja renewed\", \"NewDateTime Renewed\", each if [UnixTimestamp Renewed] = null then null else #datetimezone(1970, 1, 1, 0, 0, 0, 0, 0) + [UnixTimestamp Renewed]),",
                "    #\"Usunięto kolumny\" = Table.RemoveColumns(#\"Bezpieczna data renewed\",{\"posted\", \"renewed\", \"UnixTimestampPosted\", \"UnixTimestamp Renewed\"}),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Usunięto kolumny\",{{\"id\", type text}, {\"NewDateTimePosted\", type date}, {\"NewDateTime Renewed\", type date}}),",
                "    #\"Zmieniono nazwy kolumn\" = Table.RenameColumns(#\"Zmieniono typ\",{{\"id\", \"ID\"}, {\"NewDateTimePosted\", \"PostedDate\"}, {\"NewDateTime Renewed\", \"RenewedDate\"}})",
                "in",
                "    #\"Zmieniono nazwy kolumn\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_38665d87-a668-4f23-945d-d8ab18ba6af4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d8a95b1a-8199-4dc2-b44e-76f623978606",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7fe72f0c-7345-44b5-b72e-50c44a6b4d17",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a89c4908-94b0-4e02-a89a-ddddcd4b7477",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "724d8aec-8bda-455b-b074-52628d0be8b0",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "86a21a0e-cb09-49b4-81d3-545f6734f74d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Kwartał \" & [Numer kwartału]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "252aa54a-8342-4c0a-8bcf-49bec6e94afd",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "23f46af6-4f63-43bb-ad0a-19882702b501",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "41942a2a-bba3-40cb-a3a9-851f3ff014fb",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "5b850034-c857-4798-9b81-ce927fe9c058",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "28fafabc-d8cb-48aa-97ef-9804cc57c25f",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "ca023837-ef4d-4f97-9a79-ed292dccdc53",
                "ordinal": 3
              }
            ],
            "lineageTag": "2509eb04-2c73-4b03-8d63-0a040d704dd8"
          }
        ],
        "isHidden": true,
        "lineageTag": "68d430c0-ec09-42dc-ae3e-613670b24b3d",
        "partitions": [
          {
            "name": "LocalDateTable_38665d87-a668-4f23-945d-d8ab18ba6af4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Time'[PostedDate])), 1, 1), Date(Year(MAX('Time'[PostedDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_815af6cc-39a4-42fc-a4c4-2fd311b72361",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8e058eb0-96b1-4af8-ad83-f34a3db79124",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "564bf0fd-415c-402e-92ba-933ca43a1b0e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "19969067-c613-4861-a5e1-3086a0cc184c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "41fae3c9-10ad-474d-8f69-5633f9629929",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "28a45117-9356-4882-a4ae-f94d0653298a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Kwartał \" & [Numer kwartału]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "40c67b64-a024-4672-8975-d72d479d6bdd",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1e3e4836-48cb-4a96-ba35-bed4b0257db9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "d67ac3e2-0eae-4ae5-86a2-0d393e153695",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "bd2ade3d-b0f0-4ca6-a23e-137a10febb07",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "e647cd39-2168-41bc-8cba-24a0266767d5",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "7d267db8-cadf-4486-aaaf-bbdf984b7481",
                "ordinal": 3
              }
            ],
            "lineageTag": "67d56b4e-928a-4986-a7f0-a2e012722159"
          }
        ],
        "isHidden": true,
        "lineageTag": "c01349ca-65ef-4d8d-a959-f7e590ae80c1",
        "partitions": [
          {
            "name": "LocalDateTable_815af6cc-39a4-42fc-a4c4-2fd311b72361",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Time'[RenewedDate])), 1, 1), Date(Year(MAX('Time'[RenewedDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Contract types DIM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Contract",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39864b73-846a-4c72-afb2-18ca18706cb7",
            "sourceColumn": "Contract",
            "summarizeBy": "none"
          },
          {
            "name": "Contract type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c29abf2-03a1-478b-881a-f3103462cf8b",
            "sourceColumn": "Contract type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "972d004e-56f1-47db-a286-349c9c7cfc06",
        "partitions": [
          {
            "name": "Contract types DIM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = #\"Salary DIM\",",
                "    #\"Usunięto inne kolumny\" = Table.SelectColumns(Źródło,{\"Contract type\"}),",
                "    #\"Usunięto duplikaty\" = Table.Distinct(#\"Usunięto inne kolumny\"),",
                "    #\"Dodano kolumnę niestandardową\" = Table.AddColumn(#\"Usunięto duplikaty\", \"Contract\", each if [Contract type] = \"b2b\" or [Contract type] = \"uod\" then Text.Upper([Contract type])",
                "else Text.Proper([Contract type]))",
                "in",
                "    #\"Dodano kolumnę niestandardową\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Currencies DIM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cdf1c64-91e6-49a7-99e5-526e4dbe414b",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "610afe22-4acd-4036-b03a-25925e1b6127",
        "partitions": [
          {
            "name": "Currencies DIM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = #\"Salary DIM\",",
                "    #\"Usunięto inne kolumny\" = Table.SelectColumns(Źródło,{\"Currency\"}),",
                "    #\"Usunięto duplikaty\" = Table.Distinct(#\"Usunięto inne kolumny\")",
                "in",
                "    #\"Usunięto duplikaty\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Technology DIM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Technology",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a4b6c5a-a15e-41dc-ae1a-8fc5584182ec",
            "sourceColumn": "Technology",
            "summarizeBy": "none"
          },
          {
            "name": "Technology Pretty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70a0237b-ba4d-43e9-ae14-c5d587364a05",
            "sourceColumn": "Technology Pretty",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7a09890e-b7b6-4a67-8c8f-594b37271e6a",
        "partitions": [
          {
            "name": "Technology DIM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Tech,",
                "    // Normalizacja tekstu ze względu na problem z usunięciem duplikatów",
                "    #\"Normalizacja tekstu\" = Table.TransformColumns(Źródło, {{\"Technology\", Text.From, type text}}),",
                "    #\"Usunięto inne kolumny\" = Table.SelectColumns(#\"Normalizacja tekstu\",{\"Technology\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Usunięto inne kolumny\", \"Technology Pretty\", each if Text.Length([Technology]) is null then \"Not specified\" else",
                "if Text.Length([Technology]) <= 3 then Text.Upper([Technology])",
                "else if List.Contains({\"Html\", \"Mysql\", \".Net\"}, [Technology])",
                "then Text.Upper([Technology])",
                "else Text.Proper([Technology])),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each ([Technology] <> null and [Technology] <> \"\")),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Filtered Rows\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Duplicates\",{{\"Technology Pretty\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Mandatory skills",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Company--title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c8161ba-7442-484c-a50f-ed7d39099b1d",
            "sourceColumn": "Company--title",
            "summarizeBy": "none"
          },
          {
            "name": "Skill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc04bb67-93ef-433f-bba2-eb245523c26f",
            "sourceColumn": "Skill",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "edec3e85-f181-4fe9-b4b3-7545dd6da270",
        "partitions": [
          {
            "name": "Mandatory skills",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\dzied\\OneDrive\\Desktop\\NoFluffJobs\\mandatory_skills.csv\"),[Delimiter=\";\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Promoted Headers\",{{\"Company--title\", Text.Trim, type text}}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Company--title\", Text.Clean, type text}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Cleaned Text\",{{\"Company--title\", Text.Upper, type text}})",
                "in",
                "    #\"Uppercased Text\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Optional skills",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Company--title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9953a4b-a878-4524-8e6e-bb632de0b219",
            "sourceColumn": "Company--title",
            "summarizeBy": "none"
          },
          {
            "name": "Skill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "001ee9cc-3c5d-4426-aeb5-9894424cdb01",
            "sourceColumn": "Skill",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bb50cda8-779e-4fdd-b32b-b42e364823e5",
        "partitions": [
          {
            "name": "Optional skills",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\dzied\\OneDrive\\Desktop\\NoFluffJobs\\optional_skills.csv\"),[Delimiter=\";\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Promoted Headers\",{{\"Company--title\", Text.Trim, type text}}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Company--title\", Text.Clean, type text}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Cleaned Text\",{{\"Company--title\", Text.Upper, type text}})",
                "in",
                "    #\"Uppercased Text\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Location DIM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14ee7c05-8b0d-4b74-b2fd-71ce32b0e104",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abb4764f-c014-4c81-943a-37369e474afd",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "LocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "decd6d12-1d14-4819-a995-75adbcfedccb",
            "sourceColumn": "LocationID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e4bc7fec-8064-4002-9fbc-793ca4d8daa1",
        "partitions": [
          {
            "name": "Location DIM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = posting,",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(Source, \"Column1\", {\"location\"}, {\"Column1.location\"}),",
                "    #\"Expanded Column1.location\" = Table.ExpandRecordColumn(#\"Expanded Column1\", \"Column1.location\", {\"places\"}, {\"Column1.location.places\"}),",
                "    #\"Expanded Column1.location.places\" = Table.ExpandListColumn(#\"Expanded Column1.location\", \"Column1.location.places\"),",
                "    #\"Expanded Column1.location.places1\" = Table.ExpandRecordColumn(#\"Expanded Column1.location.places\", \"Column1.location.places\", {\"city\", \"country\"}, {\"Column1.location.places.city\", \"Column1.location.places.country\"}),",
                "    #\"Expanded Column1.location.places.country\" = Table.ExpandRecordColumn(#\"Expanded Column1.location.places1\", \"Column1.location.places.country\", {\"name\"}, {\"Column1.location.places.country.name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Column1.location.places.country\",{{\"Column1.location.places.city\", \"City\"}, {\"Column1.location.places.country.name\", \"Country\"}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Renamed Columns\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Duplicates\",{{\"City\", type text}, {\"Country\", type text}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"City\", Order.Ascending}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Sorted Rows\", \"LocationID\", each [Country] & \"-\" & [City]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"LocationID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Category DIM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3958158-8ac0-49d7-82e9-f2dd10d35814",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Category - Pretty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ccc882b-beeb-4326-8afd-7de83e55424d",
            "sourceColumn": "Category - Pretty",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "43005b75-be40-4b5b-b374-b9f0419d5423",
        "partitions": [
          {
            "name": "Category DIM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = posting,",
                "    #\"Rozwinięty element Column1\" = Table.ExpandRecordColumn(Źródło, \"Column1\", {\"category\"}, {\"Column1.category\"}),",
                "    #\"Usunięto duplikaty\" = Table.Distinct(#\"Rozwinięty element Column1\"),",
                "    #\"Zmieniono nazwy kolumn\" = Table.RenameColumns(#\"Usunięto duplikaty\",{{\"Column1.category\", \"Category\"}}),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Zmieniono nazwy kolumn\",{{\"Category\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Zmieniono typ\", \"Category - Pretty\", each if Text.Length([Category]) <= 3 then Text.Upper([Category])",
                "else Text.Proper([Category]))",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Salary DIM",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32f0d871-ae00-4871-8a03-5b06b46186c7",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Salary from",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a063cba-7568-4235-a363-cc97e809c402",
            "sourceColumn": "Salary from",
            "summarizeBy": "sum"
          },
          {
            "name": "Salary to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "229ad45d-e0e9-4986-8482-f36c0ae42cfb",
            "sourceColumn": "Salary to",
            "summarizeBy": "sum"
          },
          {
            "name": "Contract type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ad84ebe-ae52-427f-9413-6372ce6c8d59",
            "sourceColumn": "Contract type",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdd89a96-b348-4da7-af8c-e5898d4eeae6",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "Salary category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83049f92-4e97-4d03-ac0d-b21bdc04feaa",
            "sourceColumn": "Salary category",
            "summarizeBy": "none"
          },
          {
            "name": "Category sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b0501549-8a5d-4d05-8421-bd1f8eab51c2",
            "sourceColumn": "Category sort",
            "summarizeBy": "sum"
          },
          {
            "name": "Salary mid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Salary DIM\",\"TableItemName\":\"Salary groups\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "408e0bc3-9363-4bbc-8553-3271f37b6ce1",
            "sourceColumn": "Salary mid",
            "summarizeBy": "sum"
          },
          {
            "name": "Salary groups",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"s\",\"Entity\":\"Salary DIM\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s\"}},\"Property\":\"Salary mid\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s\"}},\"Property\":\"Salary mid\"}},\"Size\":7500.0}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF(",
              "\tISBLANK('Salary DIM'[Salary mid]),",
              "\tBLANK(),",
              "\tINT('Salary DIM'[Salary mid] / 7500) * 7500",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 0,
                      "value": 7500.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Salary DIM"
                          }
                        },
                        "Property": "Salary mid"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "96cf0bd0-d4f1-413d-b8e2-d1c014221c48",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "4b037ce1-de96-4a9f-accd-2d110edb9f11",
        "partitions": [
          {
            "name": "Salary DIM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = posting,",
                "    #\"Rozwinięty element Column1\" = Table.ExpandRecordColumn(Źródło, \"Column1\", {\"id\", \"salary\"}, {\"Column1.id\", \"Column1.salary\"}),",
                "    #\"Rozwinięty element Column1.salary\" = Table.ExpandRecordColumn(#\"Rozwinięty element Column1\", \"Column1.salary\", {\"from\", \"to\", \"type\", \"currency\"}, {\"Column1.salary.from\", \"Column1.salary.to\", \"Column1.salary.type\", \"Column1.salary.currency\"}),",
                "    #\"Zmieniono nazwy kolumn\" = Table.RenameColumns(#\"Rozwinięty element Column1.salary\",{{\"Column1.id\", \"ID\"}, {\"Column1.salary.from\", \"Salary from\"}, {\"Column1.salary.to\", \"Salary to\"}, {\"Column1.salary.type\", \"Contract type\"}, {\"Column1.salary.currency\", \"Currency\"}}),",
                "    // Rozwiązanie tymczasowe, do zastąpienia po wdrożeniu przeliczników walutowych.",
                "    #\"Dodano kolumnę niestandardową\" = Table.AddColumn(#\"Zmieniono nazwy kolumn\", \"Salary category\", each if [Salary to] < 10000 then \"Up to 10.000\" else",
                "if [Salary to] < 20000 then \"Up to 20.000\" else",
                "if [Salary to] < 30000 then \"Up to 30.000\" else ",
                "if [Salary to] < 40000 then \"Up to 40.000\" else",
                "\"More then 40.000\"),",
                "    #\"Dodano kolumnę niestandardową1\" = Table.AddColumn(#\"Dodano kolumnę niestandardową\", \"Category sort\", each if [Salary to] < 10000 then 0 else",
                "if [Salary to] < 20000 then 1 else ",
                "if [Salary to] < 30000 then 2 else ",
                "if [Salary to] < 40000 then 3 else 4),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Dodano kolumnę niestandardową1\",{{\"ID\", type text}, {\"Salary from\", Int64.Type}, {\"Salary to\", Int64.Type}, {\"Contract type\", type text}, {\"Currency\", type text}, {\"Salary category\", type text}, {\"Category sort\", Int64.Type}}),",
                "    #\"Usunięto duplikaty\" = Table.Distinct(#\"Zmieniono typ\"),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Usunięto duplikaty\", \"Salary mid\", each ([Salary from] + [Salary to]) / 2),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Salary mid\", Int64.Type}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Changed Type\",{\"ID\", \"Salary from\", \"Salary mid\", \"Salary to\", \"Contract type\", \"Currency\", \"Salary category\", \"Category sort\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Unique Jobs DIM",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3df7e23-aa31-45d3-b625-f92a85fbe740",
            "sourceColumn": "Company",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2913b00-9b02-452c-b3b6-5beb023bbc18",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Company--title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44dee5dd-8bad-4b4f-813c-53a0d5ff277a",
            "sourceColumn": "Company--title",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "13c156a6-7076-4f7f-85ea-1dbaf3b5b463",
        "partitions": [
          {
            "name": "Unique Jobs DIM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = posting,",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(Source, \"Column1\", {\"name\", \"title\"}, {\"Company\", \"Title\"}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Expanded Column1\",{{\"Title\", Text.Clean, type text}, {\"Company\", Text.Clean, type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Cleaned Text\",{{\"Title\", Text.Trim, type text}, {\"Company\", Text.Trim, type text}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Company\", Text.Upper, type text}, {\"Title\", Text.Upper, type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Uppercased Text\", \"Company--title\", each [Company] & \"--\" & [Title]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Company--title\", type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\"),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Duplicates\",{{\"Company\", Order.Ascending}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Sorted Rows\",{{\"Company\", Text.Proper, type text}, {\"Title\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Job Group",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aed12c98-784d-410e-9ab8-2de16e763b56",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "03e4aed3-566d-42b8-adc0-82a89282114a",
        "partitions": [
          {
            "name": "Job Group",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCklNzlCK1YlW8svP0y0Bc2IB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Group = _t])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}